version: '3.7'
services: 
    app:
        build: 
            context: .
        volumes: 
            - .:/go/src/work
        restart: always
        tty: true
        ports: 
            - "8080:8080"
        depends_on: 
            - db

    db:
        image: postgres:alpine
        environment: 
            POSTGRES_USER: gorm
            POSTGRES_PASSWORD: gorm
            POSTGRES_DB: gorm
        ports: 
            - 5432:5432